[project]
name = "chatgpt-micro-cap-experiment"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.108.0",
    "yfinance>=0.2.66",
]
